spring.application.name=pedidos
server.port=9080

###### DATASOURCE SQL SERVER ######
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pedidosDB;TrustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=SuaSenhaForte@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Kafka bootstrap server
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=pedidos-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.stefano.pedidos.kafka.event.PedidoEvent

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Seguranca
seguraca.jwt.secret=60fef54d-5504-4179-9d3c-68c3627eea3a
seguraca.jwt.expiration=3600000
seguraca.jwt.refresh-expiration=86400000

logging.format=json
logging.level.root=WARN
logging.level.org.springframework.kafka=WARN
logging.level.com.stefano.pedidos=INFO
