spring.application.name=pedidos

###### DATASOURCE SQL SERVER ######
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pedidosDB;TrustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=SuaSenhaForte@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

###### JPA ######
spring.jpa.show-sql=true
#spring.datasource.initialization-mode=never
#spring.jpa.hibernate.ddl-auto=update
# respeita os nomes de colunas
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl